package com.example.entertainmentstudio.model;

import java.util.ArrayList;
import java.util.List;

public class DummyDataGenerator {

    public static List<NewsItem> generateDummyNewsItems() {
        List<NewsItem> newsItems = new ArrayList<>();
        NewsItem item = new NewsItem();
        item.uid = 1;
        item.title = "Marvel Rivals: What Does SVP Mean & How Many Characters Play at a Time?";
        item.imageUrl = "https://www.comingsoon.net/wp-content/uploads/sites/3/2024/12/MixCollage-06-Dec-2024-01-01-PM-1902.jpg?w=1024";
        item.description = "Many individuals are curious to know what SVP means in the recently launched game, Marvel Rivals. The game’s story centers around Marvel heroes and villains from the multiverse taking on Doctor Doom and his variants in a battle to stop them from taking control of the new worlds. Additionally, it allows players to choose their [...]The post Marvel Rivals: What Does SVP Mean & How Many Characters Play at a Time? appeared first on ComingSoon.net - Movie Trailers, TV & Streaming News, and More.";
        item.sourceUrl = "https://www.comingsoon.net";
        item.isSaved = false;
        NewsItem item2 = new NewsItem();
        item2.uid = 2;
        item2.title = "American tenor Brian Jagde gets last-minute call to sing in La Scala's gala season premiere";
        item2.imageUrl = "https://s.abcnews.com/images/US/wirestory_a31b6d539097d696b6cb31e7998aafab_4x3_384.jpg";
        item2.description = "American tenor Brian Jagde was just wrapping up Verdi’s “La Forza del Destino” in Barcelona last month when he got a very much last-minute offer to sing the same role in La Scala’s gala season premiere this Saturday, arguably the opera world’s most precious night of the world!";
        item2.sourceUrl = "http://www.abcnews.go.com";
        item2.isSaved = false;
        NewsItem item3 = new NewsItem();
        item3.uid = 3;
        item3.title = "Is Marvel Rivals Free? Does It Have Crossplay & Cross-Progression?";
        item3.imageUrl = "https://www.comingsoon.net/wp-content/uploads/sites/3/2024/12/Marvel-Rivals-faq.jpg?w=1024";
        item3.description = "Fans are wondering whether Marvel Rivals is free and if it includes crossplay and cross-progression. This new hero shooter, developed by NetEase Games, allows players to choose from over 33 heroes and villains from the Marvel Universe in unique PvP matches. Here are all your important questions answered. Is Marvel Rivals free? Yes, Marvel Rivals [...]The post Is Marvel Rivals Free? Does It Have Crossplay & Cross-Progression? appeared first on ComingSoon.net - Movie Trailers, TV & Streaming News, and More";
        item3.sourceUrl = "https://www.comingsoon.net";
        item3.isSaved = false;
        NewsItem item4 = new NewsItem();
        item4.uid = 4;
        item4.title = "Dick Van Dyke Jokes About His Age Ahead of 99th Birthday";
        item4.imageUrl = "https://www.usmagazine.com/wp-content/uploads/2024/12/dick-van-dyke-jokes-about-age-ahead-of-99-birthday-2156603118.jpg";
        item4.description = "Veteran actor Dick Van Dyke is soon set to celebrate his 99th birthday – and he’s marking the occasion with a guest TV appearance. The Mary Poppins star, who will turn 99 on Friday, December 13, appeared on Jimmy Kimmel Live! on Thursday, December 5. Van Dyke was joined by Chris Martin for the TV ";
        item4.sourceUrl = "https://www.usmagazine.com";
        item4.isSaved = false;
        NewsItem item5 = new NewsItem();
        item5.uid = 5;
        item5.title = "Keira Knightley says she was ‘stalked' amid ‘Pirates of the Caribbean' fame";
        item5.imageUrl = "https://media.necn.com/2024/12/GettyImages-2188069190.jpg?fit=5779%2C3846&quality=85&strip=all";
        item5.sourceUrl = "https://www.necn.com";
        item5.description = "Originally appeared on E! OnlineKeira Knightley is revealing the sobering realities behind the overnight fame she experienced at the start of her career.“My jaw dropped at the time,” Knightley told The Los Angeles Times of the treatment she received by the media in the early 2000s. “I didn’t think it was OK at the time. I was very clear on it being absolutely shocking.”“There was an amount of gaslighting to be told by a load of men that ‘you wanted this,'” she continued. “It was rape speak. You know, ‘This is what you deserve.’ It was a very violent, misogynistic atmosphere.”The actress, 39, followed up her breakout role in 2002’s “Bend It Like Beckham” with back-to-back appearances in “Pirates of the Caribbean: The Curse of the Black Pearl” and “Love, Actually,” both of which she filmed at the age of 17 and were released when she was 18 in 2003.She recalled that the overwhelming attention she received as a result crossed a line.Celebrity NewsDec 1Keira Knightley stuns Cher by playing ‘Believe' on her teethCelebrity NewsNov 25Keira Knightley details how her family life affected her acting careerPHOTOS: Keira Knightley’s Best Roles“They very specifically meant I wanted to be stalked by men,” Knightley explained. “Whether that was stalking because somebody was mentally ill, or because people were earning money from it — it felt the same to me. It was a brutal time to be a young woman in the public eye.";
        item5.isSaved = false;
        NewsItem item6 = new NewsItem();
        item6.uid = 6;
        item6.title = "The true story behind the late Jenni Rivera's biopic ‘Jenni'";
        item6.imageUrl = "https://media.necn.com/2024/06/GettyImages-102816477.jpg?fit=3859%2C2267&quality=85&strip=all";
        item6.sourceUrl = "https://www.necn.com";
        item6.description = "“Jenni,” the new Vix biopic, tells the tragic story of the late Mexican-American singer Jenni Rivera.The movie follows the artist’s humble beginnings in Long Beach, California, her tumultuous marriages, the rise of her successful career as one the top female regional Mexican singers, and her untimely death on Dec. 9, 2012.Twelve years after her fatal airplane crash, actor Annie Gonzalez brings “La Diva de la Banda” to life, showcasing Rivera’s talent, resilience and strength amid her struggles with teen pregnancy, domestic violence and more. Directed by Gigi Saul Guerrero with a script co-written by Kate Lanier and Shane McKenzie, Manuel Uriza, Cinthya Carmona, Jero Medina and Miguel Angel Garcia co-star.Now in select theaters and available on the Spanish-language streaming service Vix, read on to learn more about the true story of Jenni Rivera and the biographical film.Celebrity NewsJul 8Daughter of Jenni Rivera says her mother's star on Hollywood's Walk of Fame was vandalizedJun 27Elated fans gather in Hollywood for unveiling of Jenni Rivera's Walk of Fame starJenni Rivera and her famous familyJenni Rivera was born July 2, 1969 in Long Beach, California, to parents Pedro Rivera and Rosa Saavedra.She was one of six children, which also include Pedro Rivera Jr., Gustavo Rivera, Lupillo Rivera, Juan Rivera and Rosie Rivera. The Riveras were a musical household and as “Jenni” depicts, her father encouraged her to get into music.";
        item6.isSaved = false;
        NewsItem item7 = new NewsItem();
        item7.uid = 7;
        item7.title = "NCIS team heads to Mexico in new episode as character Leroy Jethro Gibbs confronts past";
        item7.imageUrl = "https://i2-prod.themirror.com/incoming/article846215.ece/ALTERNATES/n615/0_NCIS_0004_Camada-1.jpg";
        item7.sourceUrl = "https://www.themirror.com";
        item7.description = "In the upcoming NCIS: Origins episode Vivo O Muerto, young Leroy (Austin Stowell) has to tackle his issues again when he gets a case that brings up the skeletons of his past";
        item7.isSaved = false;
        NewsItem item8 = new NewsItem();
        item8.uid = 8;
        item8.title = "Bychkov conducts through pain to celebrate Czech Music with North American tour";
        item8.imageUrl = "https://bloximages.newyork1.vip.townnews.com/whig.com/content/tncms/assets/v3/editorial/5/61/561fffb1-4ed7-51c5-a294-f835ee39d86d/67532b55efff0.image.jpg?resize=300%2C200";
        item8.sourceUrl = "https://www.whig.com";
        item8.description = "Celebrating the end of the 100th anniversary Year of Czech Music, an event held every decade in the year ending in 4, Semyon Bychkov is conducting through pain in leading the Czech Philharmonic on a North American tour to New...";
        item8.isSaved = false;
        NewsItem item9 = new NewsItem();
        item9.uid = 9;
        item9.title = "A Handheld History Is 50% Off At Amazon, And It's The Perfect Gift For Portable Gaming Enthusiasts";
        item9.imageUrl = "https://www.gamespot.com/a/uploads/screen_medium/1701/17013431/4392801-lostincult.jpg";
        item9.sourceUrl = "https://www.gamespot.com";
        item9.description = "A Handheld History (Hardcover) $20 (was $40) See at Amazon The Console Chronicles (Hardcover) $32 (was $40) See at Amazon Joysticks to Haptics $40 | Releases June 10, 2025 Preorder at Amazon A Handheld History, one of the best books about portable gaming, is on sale for 50% off at Amazon. Created by Lost in Cult and Retro Dodo, A Handheld History explores the rich history of portable consoles and the major games that they are remembered by. A Handheld History has never been on sale for this cheap, so snag this entertaining and insightful hardcover book for $20 while you can. If you're shopping for a retro gamer this holiday, A Handheld History would be an awesome gift.You can also save on Lost in Cult's newest book, The Console Chronicles, which does for home consoles what A Handheld History does for portables.Continue Reading at GameSpot";
        item9.isSaved = false;
        NewsItem item10 = new NewsItem();
        item10.uid = 10;
        item10.title = "British TV Presenter Fearne Cotton Reveals Her Upcoming Surgery to Remove Tumors";
        item10.imageUrl = "https://img.theepochtimes.com/assets/uploads/2024/12/04/id5771146-GettyImages-2153446086-e1733356336878-1080x720.jpg";
        item10.sourceUrl = "https://www.theepochtimes.com";
        item10.description = "The 43-year-old discovered two tumors resting on her jaw, one located on the saliva gland.";
        item10.isSaved = false;
        NewsItem item11 = new NewsItem();
        item11.uid = 11;
        item11.title = "Ruby slippers worn by Judy Garland in 'The Wizard of Oz' to be auctioned nearly 20 years after theft";
        item11.imageUrl = "https://s.abcnews.com/images/US/wirestory_6d5ccf8af71e1d7941d6f01ae4653b76_4x3_384.jpg";
        item11.sourceUrl = "http://www.abcnews.go.com";
        item11.description = "Nearly two decades after a pair of ruby slippers that were worn by Judy Garland in “The Wizard of Oz” were stolen from a Minnesota museum, the iconic shoes are set to be auctioned off to the highest bidder Saturday";
        item11.isSaved = false;
        NewsItem item12 = new NewsItem();
        item12.uid = 12;
        item12.title = "Ruby slippers worn by Judy Garland in 'The Wizard of Oz' to be auctioned nearly 20 years after theft";
        item12.imageUrl = "https://bloximages.newyork1.vip.townnews.com/reflector.com/content/tncms/assets/v3/editorial/8/68/8683d122-c26b-5117-882b-956eadcd5932//67543e330e2d4.image.jpg?resize=300%2C200";
        item12.sourceUrl = "https://www.reflector.com";
        item12.description = "Nearly two decades after a pair of ruby slippers that were worn by Judy Garland in “The Wizard of Oz” were stolen from a Minnesota museum, the iconic shoes are set to be auctioned off to the highest bidder Saturday....";
        item12.isSaved = false;
        newsItems.add(item);
        newsItems.add(item2);
        newsItems.add(item3);
        newsItems.add(item4);
        newsItems.add(item5);
        newsItems.add(item6);
        newsItems.add(item7);
        newsItems.add(item8);
        newsItems.add(item9);
        newsItems.add(item10);
        newsItems.add(item11);
        newsItems.add(item12);
        return newsItems;
    }
}
